set -e
set -x

rex -dp_comm_string 1,ececomp5.ecn.purdue.edu,33627 -V -m -pd -I# -tech /package/eda/cadence/gpdk045/gpdk045_v_6_0/qrc/typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -Ply np_rpoly_0conn -er np_rmetal7_0conn,metal7_conn.den:np_rmetal6_0conn,metal6_conn.den:np_rmetal5_0conn,metal5_conn.den:np_rmetal4_0conn,metal4_conn.den:np_rmetal3_0conn,metal3_conn.den:np_rmetal2_0conn,metal2_conn.den:np_rmetal1_0conn,metal1_conn.den -rP res.mod -mp mprexa1kJR4I np_rmetal1_0conn::metal1_conn_cut - rcont_0poly,1,T rcont_0pdiff_metal1_0conn_pdiff_0conn,1,t rcont_0ndiff_metal1_0conn_ndiff_0conn,1,t rVia1,1,x - L1T0,1,I

rex -dp_comm_string 2,ececomp5.ecn.purdue.edu,33627 -V -m -pd -I# -tech /package/eda/cadence/gpdk045/gpdk045_v_6_0/qrc/typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -Ply np_rpoly_0conn -er np_rmetal7_0conn,metal7_conn.den:np_rmetal6_0conn,metal6_conn.den:np_rmetal5_0conn,metal5_conn.den:np_rmetal4_0conn,metal4_conn.den:np_rmetal3_0conn,metal3_conn.den:np_rmetal2_0conn,metal2_conn.den:np_rmetal1_0conn,metal1_conn.den -rP res.mod -mp mprexammIdEi np_rmetal2_0conn::metal2_conn_cut - rVia2,1,x rVia1,1,T

rex -dp_comm_string 3,ececomp5.ecn.purdue.edu,33627 -V -m -pd -I# -tech /package/eda/cadence/gpdk045/gpdk045_v_6_0/qrc/typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -Ply np_rpoly_0conn -er np_rmetal7_0conn,metal7_conn.den:np_rmetal6_0conn,metal6_conn.den:np_rmetal5_0conn,metal5_conn.den:np_rmetal4_0conn,metal4_conn.den:np_rmetal3_0conn,metal3_conn.den:np_rmetal2_0conn,metal2_conn.den:np_rmetal1_0conn,metal1_conn.den -rP res.mod -mp mprexa9MwoKW np_rpoly_0conn::poly_conn_cut - _0pmos1v_mgvia,1,z _0nmos1v_mgvia,1,z rcont_0poly,1,x

rex -dp_comm_string 4,ececomp5.ecn.purdue.edu,33627 -V -m -pd -I# -tech /package/eda/cadence/gpdk045/gpdk045_v_6_0/qrc/typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -Ply np_rpoly_0conn -er np_rmetal7_0conn,metal7_conn.den:np_rmetal6_0conn,metal6_conn.den:np_rmetal5_0conn,metal5_conn.den:np_rmetal4_0conn,metal4_conn.den:np_rmetal3_0conn,metal3_conn.den:np_rmetal2_0conn,metal2_conn.den:np_rmetal1_0conn,metal1_conn.den -rP res.mod -mp mprexaulMZq8 np_rmetal3_0conn::metal3_conn_cut - rVia3,1,x rVia2,1,T

rex -dp_comm_string 5,ececomp5.ecn.purdue.edu,33627 -V -m -pd -I# -tech /package/eda/cadence/gpdk045/gpdk045_v_6_0/qrc/typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -Ply np_rpoly_0conn -er np_rmetal7_0conn,metal7_conn.den:np_rmetal6_0conn,metal6_conn.den:np_rmetal5_0conn,metal5_conn.den:np_rmetal4_0conn,metal4_conn.den:np_rmetal3_0conn,metal3_conn.den:np_rmetal2_0conn,metal2_conn.den:np_rmetal1_0conn,metal1_conn.den -rP res.mod -mp mprexae6Fm4a np_rmetal4_0conn::metal4_conn_cut - rVia4,1,x rVia3,1,T

rex -dp_comm_string 6,ececomp5.ecn.purdue.edu,33627 -V -m -pd -I# -tech /package/eda/cadence/gpdk045/gpdk045_v_6_0/qrc/typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -Ply np_rpoly_0conn -er np_rmetal7_0conn,metal7_conn.den:np_rmetal6_0conn,metal6_conn.den:np_rmetal5_0conn,metal5_conn.den:np_rmetal4_0conn,metal4_conn.den:np_rmetal3_0conn,metal3_conn.den:np_rmetal2_0conn,metal2_conn.den:np_rmetal1_0conn,metal1_conn.den -rP res.mod -mp mprexadXL1nM np_rmetal5_0conn::metal5_conn_cut - rVia5,1,x rVia4,1,T

rex -dp_comm_string 7,ececomp5.ecn.purdue.edu,33627 -V -m -pd -I# -tech /package/eda/cadence/gpdk045/gpdk045_v_6_0/qrc/typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -Ply np_rpoly_0conn -er np_rmetal7_0conn,metal7_conn.den:np_rmetal6_0conn,metal6_conn.den:np_rmetal5_0conn,metal5_conn.den:np_rmetal4_0conn,metal4_conn.den:np_rmetal3_0conn,metal3_conn.den:np_rmetal2_0conn,metal2_conn.den:np_rmetal1_0conn,metal1_conn.den -rP res.mod -mp mprexa2XRBuo np_rmetal6_0conn::metal6_conn_cut - rVia6,1,x rVia5,1,T

rex -dp_comm_string 8,ececomp5.ecn.purdue.edu,33627 -V -m -pd -I# -tech /package/eda/cadence/gpdk045/gpdk045_v_6_0/qrc/typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -Ply np_rpoly_0conn -er np_rmetal7_0conn,metal7_conn.den:np_rmetal6_0conn,metal6_conn.den:np_rmetal5_0conn,metal5_conn.den:np_rmetal4_0conn,metal4_conn.den:np_rmetal3_0conn,metal3_conn.den:np_rmetal2_0conn,metal2_conn.den:np_rmetal1_0conn,metal1_conn.den -rP res.mod -mp mprexaurKuNQ np_rmetal7_0conn::metal7_conn_cut - rVia6,1,T

rexmerge -V -N NET -n mprexa9MwoKW,mprexa1kJR4I,mprexammIdEi,mprexaulMZq8,mprexae6Fm4a,mprexadXL1nM,mprexa2XRBuo,mprexaurKuNQ -b np_rpoly_0conn::Rnp_rpoly_0conn.dev2,np_rmetal1_0conn::Rnp_rmetal1_0conn.dev2,np_rmetal2_0conn::Rnp_rmetal2_0conn.dev2,np_rmetal3_0conn::Rnp_rmetal3_0conn.dev2,np_rmetal4_0conn::Rnp_rmetal4_0conn.dev2,np_rmetal5_0conn::Rnp_rmetal5_0conn.dev2,np_rmetal6_0conn::Rnp_rmetal6_0conn.dev2,np_rmetal7_0conn::Rnp_rmetal7_0conn.dev2 -l ,L1T0,,,,,, np_rpoly_0conn.res,np_rmetal1_0conn.res,np_rmetal2_0conn.res,np_rmetal3_0conn.res,np_rmetal4_0conn.res,np_rmetal5_0conn.res,np_rmetal6_0conn.res,np_rmetal7_0conn.res

